services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs-backend
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - MONGODB_URI=mongodb://51.210.177.195:27017/si-mi-base-de-datos
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/letsencrypt
    expose:
      - 80
      - 443
    depends_on:
      - backend
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge